spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm99697
    password: 111294
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 80